### ISSUE TITLE
Plutarch 1.1

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#106]
This is a chance to do breaking changes, but we should still keep it to a minimum.

Please post suggestions.

My suggestion:

```haskell
type Term :: (a :: k -> Type) -> (s :: k) -> Type
```
to
```
data S
type Term :: (a :: S -> Type) -> (s :: S) -> Type
```

This would fix a ton of headaches wrt. type inference, functional dependencies, and probably many other things, while still keeping illegal terms illegal.

**Comment by TotallyNotChase** [comment]
How about we rename some types, or at the very least, relocate them? `PMaybe` and similar comes to mind - not clear whether its a builtin data or scott encoded type. Related: #56 

Some more convenient exports right in `Plutarch.Prelude` would be nice. I feel like we have enough things now such that users won't need the unsafe functions either. If they do, it'll be quite rare. So #28 is something to think about.

I assume you're already thinking of the `PLift` and `DefaultUni` issues raised, so there's that.

Maybe controversial opinion, but I feel like some of the types that can be trivially created using `pconstant` (in all scenarios, i.e they don't contain `Term`s) shouldn't have a `PlutusType` instance. Or at least, not a `PCon` instance. Especially `PUnit`.....

**Comment by blamario** [comment]
We can try to rename, and ideally reduce the number of, various types and constructors. I for one have serious trouble assigning meanings and distinguishing between `PData`, `PAsData`, `PIsData`, `PIsDataRepr`, and `PIsDataReprRepr`.

**Comment by L-as** [comment]
Unsafe functions are already not in the prelude, not sure what you mean by that.

**Comment by L-as** [comment]
`pcon` is pretty fundamental, especially once do-notation is added to the mix.

**Comment by TotallyNotChase** [comment]
> Unsafe functions are already not in the prelude, not sure what you mean by that.

I meant the unsafe function exports from the `Plutarch` module. It is pretty essential to import that module as it stands; I'm just slightly concerned about it also exporting unsafe functions

**Comment by t1lde** [comment]
Some pre-emptive module reorganization could be worth it, the codebase is starting to get big.

Some suggestions:

- Organize plutus builtin types separately (`Builtin` as submodule/s?)
  - Plutarch.Builtin 
  - Plutarch.Builtin.etc
- Section some `unsafe_` functions to Plutarch.Unsafe
- Types (or better name) submodules for (scott or not) encoded types and their utils 
  - Plutarch.Types.List  (`ListLike` moved to it's own module probably too)
  - Plutarch.Types.etc
 - Putarch.Api.V1 is pretty huge, might be worth splitting and re-exporting. We'll start to want util modules for API types anyway.

**Comment by t1lde** [comment]
some naming suggestions for @blamario's concerns -

- `PIsDataRepr` -> `PConstrRepr` (since it only really encodes constr)

taking a cue from generics-sop: 
- `PIsDataReprRepr` -> `PSOP`, or `PCode`... or to be more verbose, `PConstrEncoding`

**Comment by L-as** [comment]
Two other things:
- I really want do-notation. We can do something with [QualifiedDo](https://downloads.haskell.org/ghc/latest/docs/html/users_guide/exts/qualified_do.html).
- We probably want to rename `PDataList` to e.g. `PTuple`, `PDataHList`, `PHListData`, or something else.

**Comment by L-as** [comment]
Definitely agree. @kozross

**Comment by emiflake** [comment]
It would be nice if bumping plutus lower-bound requires a minor version bump for plutarch. Bumping plutus frequently comes with incompatibilities with other libraries (e.g. plutus-extra, which upon bumping plutus bumps a *major* version) and needs to be *really* necessary, e.g. for GHC bumping reasons. Compatibility with plutus-extra is quite desirable I find for plutarch, since they should theoretically play really nice together, so it's something to keep in mind. @L-as

**Comment by srid** [comment]
> How about we rename some types, or at the very least, relocate them? `PMaybe` and similar comes to mind - not clear whether its a builtin data or scott encoded type. Related: #56

I think this should also apply to `Plutarch.Rec` because IIUC that defines Scott-encoded records. Should be more like `Plutarch.ScottEncoded.Rec` or `Plutarch.Types.ScottEncoded.Rec` for avoiding misunderstanding.

**Comment by L-as** [comment]
`.Rec` is for mutually recursive values. Data-encoded recursion makes no sense.

**Comment by blamario** [comment]
I named it `.Rec` because it can ambiguously refer both to mutually-recursive values and to records in general. It already contains functionality for both, and there should be more to come. I'm open to suggestions if anybody finds it confusing.

**Comment by L-as** [comment]
#99 is essentially 1.1. We probably want to add release notes, etc. before merging.

**Comment by L-as** [comment]
OTOH many people are waiting for staging to land, so perhaps we should do the release notes later.

**Comment by L-as** [comment]
Thanks everyone for helping on this!
