### ISSUE TITLE
GitHub PR: benchmark diff

### ISSUE THREAD

**Issue by srid** [Plutonomicon/plutarch#123]
Produce reports like [this](https://github.com/input-output-hk/plutus/pull/3494#issuecomment-874588174) for PRs in this repo, so that we can assess the impact of the PRs on benchmarks (code size, cpu & men). Take `bench.csv` produced by Hercules Effects for both commit A (commit where the PR branch branched off) and commit B (PR commit), and diff them.

---

https://github.com/Plutonomicon/plutarch/pull/87 is an example of such PR which improved the `types:builtin:intlist:plistEquals` benchmark.

[Old](https://hercules-ci.com/accounts/github/Plutonomicon/derivations/%2Fnix%2Fstore%2Fi4gy7rp596lk0rq75yhwgc4rmk0a4zi3-benchmark.drv/log?via-job=494e885c-d1e9-4eb2-b76f-247059eaebf5)

```
types:builtin:intlist:plistEquals:==(n=3)            25843624(cpu)  59392(mem)  180(bytes)
types:builtin:intlist:plistEquals:/=(n=4)            12939651(cpu)  30928(mem)  181(bytes)
types:builtin:intlist:plistEquals:/=(empty;n=3)       7497147(cpu)  19064(mem)  177(bytes)
```

[New](https://hercules-ci.com/accounts/github/Plutonomicon/derivations/%2Fnix%2Fstore%2Frnz3dlw59wiv6hl8i7864lb0r23grl8d-benchmark.drv/log?via-job=3fee9a77-90c8-49a3-9b85-b02eecf89cad)

```
types:builtin:intlist:plistEquals:==(n=3)             9398080(cpu)  20846(mem)  95(bytes)
types:builtin:intlist:plistEquals:/=(n=4)             9398080(cpu)  20846(mem)  96(bytes)
types:builtin:intlist:plistEquals:/=(empty;n=3)       1639885(cpu)   4664(mem)  92(bytes)
```

Diff'ing these two tables, we would add a comment to the PR showing the number differences for each row/column much like the Plutus report. In the Plutus repo, benchmark reporting is manually triggered by adding a PR comment containing `/benchmark`.

**Comment by emiflake** [comment]
I was looking into implementing this. With Hercules, how would we create artifacts that we can use as means for comparison? It doesn't seem like Hercules publishes the bench.csv anywhere, or am I missing something?

**Comment by srid** [comment]
@nixinator @MatthewCroughan Could one of you help Emily here?

The nix flake check writes a file called `bench.csv` - we want Hercules to upload it somewhere. The check is run here: https://hercules-ci.com/accounts/github/Plutonomicon/derivations/%2Fnix%2Fstore%2F1nzsljyb7yv6fhjgg1p34kz1acrnm568-benchmark.drv/log?via-job=b6899b8f-ead0-43f6-90e0-5fba98df65c8

I vaguely recall seeing Hercules effects supporting artifact upload. Perhaps we can use that.

**Comment by MatthewCroughan** [comment]
We do not need to write the CSV in order to accomplish this. Doing so would not be a good benchmark either, as the benchmark might be effected by different processes running on the CI agent at a future time. Instead, we can simply perform two benchmarks in a single job, using two different revisions of the source code, which generates a new CSV, which is the diff of the two.

**Comment by srid** [comment]
> the benchmark might be effected by different processes running on the CI agent at a future time.

Usually, yes - but for _this_ project we don't care about that, because the specific benchmark metrics (code size, cpu/mem "budget") are calculated _independent_ of the running machine's performance.

**Comment by srid** [comment]
#144

**Comment by srid** [comment]
@emiflake @MatthewCroughan How do I get to the benchmark diff for a PR, say #173 ?

**Comment by emiflake** [comment]
> How do I get to the benchmark diff for a PR

Hah, this is what I've been asking. But AFAICT we just need to drop the `runIf`. I'll quickly see if it works on a non-PR as well, if so I'll make a PR for it :)

**Comment by TotallyNotChase** [comment]
@srid is this still relevant?
