### ISSUE TITLE
Add helper for deriving via newtypes

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#126]
A "newtype" in Plutarch is of the form:

```haskell
newtype A = A (Term s B)
```

We want to be able to derive all the relevant instances. We probably want to make a generic `DerivePNewtype` data type or similar. (Name up for bike-shedding)

This is needed for the types in `Plutarch.Api.V1`, since right now most of the types lack a `PlutusType` instance and similar.

**Comment by TotallyNotChase** [comment]
I've been getting by with manual impls; not entirely sure whether I can generalize these-
```hs
instance PlutusType PPubKeyHash where
  type PInner PPubKeyHash _ = PByteString
  pcon' (PPubKeyHash s) = s
  pmatch' x f = f $ PPubKeyHash x

instance PIsData PPubKeyHash where
  pfromData x = pcon $ PPubKeyHash $ pfromData $ coerce x
  pdata x = coerce . pdata $ pto x
```

**Comment by L-as** [comment]
I'm pretty sure you can generalise these.

**Comment by srid** [comment]
Should also support newtyping over user-defined types?

```haskell
newtype MyContext s = MyContext (PScriptContext s)
```

**Comment by L-as** [comment]
Yes of course. It would be `newtype MyContext s = MyContext (Term s PScriptContext)` though.
