### ISSUE TITLE
Generic deriving

### ISSUE THREAD

**Issue by srid** [Plutonomicon/plutarch#135]
This is a meta issue for generic deriving of various Plutarch classes.

## Typeclasses to derive 

- [x] `PIsDataRepr` (Data for non-Scott encoded types) #173 
- [x] `PlutusType` for Scott encoded types: https://github.com/Plutonomicon/plutarch/pull/189
- [x] `PlutusType` for Data: https://github.com/Plutonomicon/plutarch/issues/187
- [ ] ... what else?

**Comment by L-as** [comment]
We will probably still need something separate for newtypes.

**Comment by TotallyNotChase** [comment]
are we missing anything here?

**Comment by L-as** [comment]
Nope! Thanks to both @srid and @TotallyNotChase !

**Comment by srid** [comment]
I have an idea in mind (Data-encoded types using normal sum/records), but that can wait I suppose. What we have right now should be sufficient.

**Comment by L-as** [comment]
That can by definition not be efficient currently without punsafeLetPure and such
