### ISSUE TITLE
Add code examples demonstrating `plet`.

### ISSUE THREAD

**Issue by jhodgdev** [Plutonomicon/plutarch#147]
I think the section on [hoisting](https://github.com/Plutonomicon/plutarch/blob/master/docs/GUIDE.md#hoisting-metaprogramming--and-fundamentals) could use some code examples of how one would use `plet`.

**Comment by jhodgdev** [comment]
Apologies. I have worked further through the guide and see where `plet` examples have been introduced. Maybe reconsider a little re-order? Idk if others will work through the guide linearly like I am.

**Comment by TotallyNotChase** [comment]
That section should definitely hyperlink to the `plet` section. Thanks for letting us know!

We're definitely missing the whole "tying the knot" part in the guide which can only be achieved by reports like this. I'll update the section to have a handy pointer to `plet` usage that is further down below.

**Comment by jhodgdev** [comment]
Awesome! Ty.
