### ISSUE TITLE
Alternative backends?

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#157]
Could we generalise the language such that it is useful for more than just UPLC? What about a JS backend?

**Comment by TotallyNotChase** [comment]
This.... seems like a rather ambitious goal. Curious as to *why*? Why not just use Haskell to generate JS?

**Comment by blamario** [comment]
We could target STG, which would resolve the issue of off-chain code reuse in the other direction.

And, a funny thought, if we manage to somehow preserve types for PIR and issue #82, we might be able to also target Haskell Core.

**Comment by L-as** [comment]
> This.... seems like a rather ambitious goal. Curious as to _why_? Why not just use Haskell to generate JS?

It would have the same benefits we see now. GHCJS doesn't really work well.



> We could target STG, which would resolve the issue of off-chain code reuse in the other direction.
> 
> And, a funny thought, if we manage to somehow preserve types for PIR and issue #82, we might be able to also target Haskell Core.

I do think that's quite interesting, and possibly practical, however, there are also other interesting backends, e.g. Chez Scheme, or MLTon.

**Comment by L-as** [comment]
After thinking through this more, I don't think this is the right way to approach making eDSLs for other backends. There should be an eDSL per backend. However, what would be immensely useful is a backend-agnostic eDSL. Such an eDSL would be useful for writing general-purpose libraries in, but it would not be Plutarch.
