### ISSUE TITLE
More tests of compiled output

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#177]
There are too few tests for the compiled output. We need **a lot** more.

**Comment by L-as** [comment]
`printTerm x @?= "something"`

**Comment by srid** [comment]
With golden testing in place, this is now straight forward to do -- just add the Plutarch programs with `pgoldenSpec` and `@|`:

https://github.com/Plutonomicon/plutarch/blob/9c163c80b3df7eac3b6d2e5ab936b36584ce5316/plutarch-test/src/Plutarch/ByteStringSpec.hs#L11-L17
