### ISSUE TITLE
`pletFields` should take type-level list of fields to bind

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#182]
https://github.com/Plutonomicon/plutarch/pull/181#discussion_r791637577

This would make it the interface efficient as it can be AFAICT.

**Comment by t1lde** [comment]
I think I have an idea of how to do this, let me give it a go

**Comment by L-as** [comment]
@t1lde One (perhaps unfortunate) thing to take into account is that exposing the fields with `HasField` doesn't give warnings for when you don't use the fields. It's perhaps best to give the user the `HRec` and have them pattern match on it completely as `Labeled @"field" field`, which albeit unfortunate, AFAICT is the only way to give proper warnings for unused fields.

**Comment by t1lde** [comment]
That doesn't seem worth it to me, As long as the docs make it clear how to use it efficiently IMO convenience overrules

**Comment by L-as** [comment]
Sure.

**Comment by L-as** [comment]
It would be amazing if GHC could somehow infer the type level list from how we use it, but I don't think that's possible.
