### ISSUE TITLE
Make plutarch.cabal cleaner and add tests for GHC 8.10

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#198]
https://github.com/Plutonomicon/plutarch/issues/145#issuecomment-1022629754

**Comment by srid** [comment]
Dup in part: #145

**Comment by TotallyNotChase** [comment]
Shouldn't this be closed already?

**Comment by L-as** [comment]
We can close this when https://github.com/Plutonomicon/plutarch/blob/staging/plutarch.cabal#L153 is removed entirely.

**Comment by srid** [comment]
> We can close this when https://github.com/Plutonomicon/plutarch/blob/staging/plutarch.cabal#L153 is removed entirely.

Should be done in #302
