### ISSUE TITLE
Indicate knowledge prerequisites in GUIDE.md

### ISSUE THREAD

**Issue by peter-mlabs** [Plutonomicon/plutarch#200]
It may be helpful for adoption of Plutarch to have a list of resources of both "required" and "helpful" prerequisites for comprehension. There are a number of terms that I've seen before, but do not fully understand; a younger me would be intimidated, chase down the semantics of those terms, and likely abandon learning plutarch as "too hard". The missing resources don't actually seem to affect my current comprehension, however, so I am assuming the actual prerequisites are light. But some readers get skiddish if unfamiliar terms are not either defined or explicitly noted as inconsequential, and in the interest of lowering the barrier to entry, here are some examples:

  - It _appears_ that familiarity with UPLC is assumed. The signature `eval :: ClosedTerm a -> Either ScriptError (ExBudget, [Text], Program DeBruijn DefaultUni DefaultFun ())` is the first type signature provided, and I (personally) don't know what the last element of the triple means, except that I am told it is the script result. This may look scary to newbies, and give the false impression that Plutarch is beyond them.
  - Similarly, the concept of "Lifts" is something that I've inferred while learning haskell, but I've never had adequately explained. If a concise resource exists, it could be helpful to link. This goes for the `ST` monad as well. The current guide gives the impression that these should be obvious.
  - Scott Encoding 
  - `DefaultUni` -- this is linked later in the document, but the link is broken (since the IOHK haddock instance never seems to work....)

If someone is able to give a basic run-down of intended audience and assumed level of expertise, I'd be happy to submit edits.

**Comment by TotallyNotChase** [comment]
I want the users' guide to be as widely comprehensible as possible, without needing to chase down other docs and knowledge sources. (this doesn't apply to the developers guide)

In that sense, all of those things (and perhaps more) should definitely be clarified (minimally) within the guide itself. I'll definitely keep that in mind.

* I should've mentioned this in the guide - but those functions were meant to be "just drop it in your code and don't worry about it". You don't need to know UPLC to use or understand Plutarch.
* When you say "Lifts", do you mean the `PLift` and `PConstant` stuff? I think the staging version of the guide explains what we mean by "lifting" in this case.
* Scott encoding and data encoding should definitely be explained - I just don't know where to do that. Too much details regarding this topic should be in the developers' guide, not users' guide. But some detail is required.
* Heh, I'll update the links to point to [playground.iohk](https://playground.plutus.iohkdev.io/) instead.

**Comment by peter-mlabs** [comment]
> I should've mentioned this in the guide - but those functions were meant to be "just drop it in your code and don't worry about it". You don't need to know UPLC to use or understand Plutarch.

Yep, this was exactly the impression I got. Glad to know that was right. 

> When you say "Lifts", do you mean the PLift and PConstant stuff? I think the staging version of the guide explains what we mean by "lifting" in this case.

Just that there's these concept of "lifted" and "unlifted" types in Haskell, and then there's `PLift` and `PConstant`, and hoisting (which sounds conceptually similar) -- I'm vaguely familiar with lifted/unlifted types (and boxed/unboxed), but its not immediately apparent whether `PLift` _et al_ are conceptually related or if the term "lift" is overloaded. 

I'll check out the staging branch as well.


Thanks for your response!

**Comment by peter-mlabs** [comment]
@srid Hadn't heard of the Diátaxis Framework before, but obviously I've seen it in practice! I like that breakdown a lot. 

Thanks for the UPLC link, as well. It highlights the other benefit of linking prerequisite resources directly: the link from the plutonomicon will get me up to speed faster than [anything on the first page of search results](https://www.google.com/search?q=untyped+plutus+core&client=ubuntu&hs=eJB&channel=fs&biw=2488&bih=1291&ei=r8XyYY_DJNSuytMP96equAw&ved=0ahUKEwjP1srHqtL1AhVUl3IEHfeTCsc4ChDh1QMIDQ&uact=5&oq=untyped+plutus+core&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKsCOgcIABBHELADSgQIQRgASgQIRhgAULQEWK8FYK4GaAFwAngAgAFfiAGuAZIBATKYAQCgAQHIAQLAAQE&sclient=gws-wiz) for UPLC, and hopefully will increase discoverability of the plutonomicon itself :)
