### ISSUE TITLE
Add convenient synonyms to type constructors at the term level

### ISSUE THREAD

**Issue by TotallyNotChase** [Plutonomicon/plutarch#21]
Instead of having to write-
```hs
pcon $ PJust $ pcon PTrue
```
It'd be convenient to have-
```hs
pjust ptrue
```
(or some better names)

**Comment by L-as** [comment]
Good point.

**Comment by L-as** [comment]
After thinking about this a lot, I'm not sure this is a good idea. It saves some characteres, but it adds a lot of complexity, since you have to duplicate each data constructor definition, each import, etc. etc.

**Comment by TotallyNotChase** [comment]
Debatable. I think people will be defining synonyms either way to reduce code clutter. This package might need to fill in synonyms as well if it starts including Plutarch definitions of Plutus API utilities.

I see two solutions here, so far-
* The responsibility with defining synonyms could be offloaded to the user, which means they will probably have to define only as many synonyms as they need, but a lot of Plutarch codebases will be defining these same synonyms. 
* The responsibility is taken by Plutarch.

Either way, I don't think `pcon $ PJust $ pcon PTrue` is justifiable while writing business logic. In the end, if Plutarch itself doesn't provide the synonyms, there will probably be a utility package that defines these aliases so people can just import it instead of define every synonym everytime they need it. Which is fine - but at that point, why not just have that within the `plutarch` package itself?

**Comment by L-as** [comment]
I personally think `pcon . PJust $ pcon PTrue` is fine.

**Comment by TotallyNotChase** [comment]
This is obsolete with the existence of `pconstant` now.
