### ISSUE TITLE
Expand introduction to `pcon` in guide.

### ISSUE THREAD

**Issue by jhodgdev** [Plutonomicon/plutarch#218]
> Or from Plutarch terms within other constructors using `pcon` (requires [`PlutusType`/`PCon`](#plutustype-pcon-and-pmatch) instance)-
> 
> ```haskell
> import Plutarch.Prelude
> import Plutarch.Maybe (PMaybe (PJust))
> 
> -- | Create a plutarch level optional value from given value.
> f :: Term s (a :--> PMaybe a)
> f = plam $ \x -> pcon $ PJust x
> -- Note that 'PMaybe' has a 'PlutusType' instance.
> ```

I feel like this section of the guide could be expanded/re-written. Not by much but I don't believe the introduction to `pcon` is intuitive to those unfamiliar with Plutarch. 

I found looking up the type signature of `pcon` useful, and thereby came up with my own demonstration, which I included in my own notes:

```haskell
ghci> :t pconstant True
Term s PBool
ghci> :t PTrue
PBool s
ghci> :t pcon PTrue
Term s PBool
```

I don't know if it's the kind of thing you'd want to include but it is what made `pcon` "click" for me.

**Comment by TotallyNotChase** [comment]
Good point! Could you please take a look at this section (under `Constants`) on [this branch](https://github.com/Plutonomicon/plutarch/blob/guide-wip/docs/GUIDE.md#constants) and let me know if that clarifies things?

**Comment by jhodgdev** [comment]
Thanks for listening to my suggestion :) I've compared the branches:

> PMaybe declaration: data PMaybe a s = PJust (Term s a) | PNothing
> 
> Aside: Notice that pcon actually takes in a Plutarch type to create a Plutarch term. In particular, PJust x (x :: Term s a), has type PMaybe a s. Thus, this pcon usage has type PMaybe a s -> Term s (PMaybe a). Similarly, pcon PNothing would yield forall x. Term s (PMaybe x). As PNothing has type PMaybe x s.
> 

If I am not mistaken this is the only difference between the guide on that branch and master? I find the declaration of `PMaybe` beneficial. I think the aside is overall an improvement. 

> Notice that pcon actually takes in a Plutarch type to create a Plutarch term.

This is very helpful.

> In particular, PJust x (x :: Term s a), has type PMaybe a s. Thus, this pcon usage has type PMaybe a s -> Term s (PMaybe a). Similarly, pcon PNothing would yield forall x. Term s (PMaybe x). As PNothing has type PMaybe x s.

I find this a little rushed or too condensed? I certainly think that 'in-line' code statements this complex are difficult to read and should definitely be put in their own block. 

> yield forall x. Term s (PMaybe x). As PNothing has type PMaybe x s.

', as `PNothing` has type `PMaybe x s`'. Bad form to start a sentence with 'as'.

**Comment by TotallyNotChase** [comment]
Good points, thanks! I modified it a bit, could you please check that section one more time?

**Comment by TotallyNotChase** [comment]
That's not really doable without a restructure since that section follows a pattern like-
> built by <method>
> 
> <example>
> 
> Or by <another method>
>
> <example>
>
> Or by <another another method>
>
> <example>

So it'd need a organizational restructure to inline that "aside". Probably just going to leave it as is for now ¯\\_(ツ)_/¯

**Comment by jhodgdev** [comment]
Sure thing :) thanks for taking my thoughts on-board.

**Comment by TotallyNotChase** [comment]
Actually, let's not close this just yet - the guide updates are still WIP. Soon though!
