### ISSUE TITLE
Add utility `pfield` and `pletFields` variants that automatically `pfromData` the result

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#235]

**Comment by TotallyNotChase** [comment]
On a related note, why aren't the types used in `pletFields` and `pfield`'s context exported? People can't write general utilities wrapping around `pletFields`/`pfield` without them.

**Comment by L-as** [comment]
They're supposed to be implementation details. You can always import the internal modules, which exposes you to potential breakage.

**Comment by TotallyNotChase** [comment]
Well, the internal modules still don't export `Bindings` - which is needed in the context.

**Comment by L-as** [comment]
If you feel that it is necessary, you could export it.
