### ISSUE TITLE
Add `List` type

### ISSUE THREAD

**Issue by srid** [Plutonomicon/plutarch#3]
Decide between Scott encoding and Plutus builtin primitives (`ChooseList`, `HeadList`, ..). Compare CPU costs, code size, etc.

Goal: we need list type for the signatories in #5

**Comment by srid** [comment]
@L-as added a List type using UPLC builtins here: https://github.com/Plutonomicon/plutarch/commit/24acc6bbf83d3b94abc9dcd4913ccc44edb2dfc4

**Comment by L-as** [comment]
As I've noted elsewhere, we need a Scott-encoded lists so that we can have a list of arbitrary data structures using Scott encodings.

**Comment by srid** [comment]
A lot has changed since this issue was opened, so closing.
