### ISSUE TITLE
Port and retire `./examples` and `./plutarch-benchmark/bench`

### ISSUE THREAD

**Issue by srid** [Plutonomicon/plutarch#302]
The tests and benchmarks in these packages should be ported to `./plutarch-test`. Then the packages should be removed.

`plutarch-benchmark` library itself should still exist (or maybe subsumed under `Plutarch.Test` unless backwards compat is relevant).

**Comment by TotallyNotChase** [comment]
I'd like the `plutarch-benchmark` library to be a separate library for users to depend on. And we should keep maintaining it.
