### ISSUE TITLE
More informative errors on `plift`

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#319]
The constructors for `ReadKnownError` aren't exported, but some prisms are. https://github.com/input-output-hk/plutus/blob/0397f83b8298ba1b3c531511172637651b624164/plutus-core/plutus-core/src/PlutusCore/Builtin/KnownType.hs#L158

**Comment by TotallyNotChase** [comment]
Is it ok to add the lens dependency for tackling this?

**Comment by L-as** [comment]
We already depend on lens indirectly.
