### ISSUE TITLE
Switch to tasty and plutus-golden

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#331]
sydtest is under a non-commercial license: https://github.com/NorfairKing/sydtest/blob/master/sydtest/LICENSE.md

This is quite a big problem.

@NorfairKing
@srid 

We can try converting to `tasty`, but we need to vendor the golden file logic probably. See https://github.com/Liqwid-Labs/plutus-extra/tree/master/plutus-golden

**Comment by srid** [comment]
> https://github.com/NorfairKing/sydtest/blob/master/sydtest/LICENSE.md

I *think* the license Plutarch (and its users) has for sydtest is different to this one. I will let @NorfairKing clarify.

**Comment by L-as** [comment]
![image](https://user-images.githubusercontent.com/22075344/155519096-f5d0b1f5-1c38-4820-948a-fdda1af3782b.png)

Seems like we'll have to switch to something else if others are to use `plutarch-test`.

**Comment by L-as** [comment]
@kozross might be interested in this

**Comment by kozross** [comment]
Yeah, I would say a switch-away is essential here. I'm happy to help with this effort.

**Comment by L-as** [comment]
That would be really helpful. The biggest potential issue seems to be that tasty does not tell us where we are in the test hierarchy we are for figuring out the names of the golden files.

**Comment by kozross** [comment]
`tasty` (and any stuff built atop it) does golden tests quite badly in my experience.

**Comment by kozross** [comment]
`tasty` is significantly better than `hspec` in my experience, from the perspective of documentation, usability and extensibility.

**Comment by NorfairKing** [comment]
> tasty is significantly better than hspec in my experience, from the perspective of documentation, usability and extensibility.

My experience contradicts this, fwiw. See the comparison table here:
https://github.com/NorfairKing/sydtest#features--comparison-to-similar-projects

**Comment by srid** [comment]
@kozross, I'd be interested to hear which test runner you plan to adopt and how it will impact the goldens tree syntax we have now (it relies on sydtest's monadic test spec hierarchy to compute the filename).

Ideally, we want to keep changes to the `Plutarch.API` exports minimal, and just swap out the internals.

**Comment by L-as** [comment]
https://github.com/NorfairKing/sydtest/pull/39
