### ISSUE TITLE
Plutarch 1.1.0 does not compile in plutus-starter

### ISSUE THREAD

**Issue by zypeh** [Plutonomicon/plutarch#342]
I got this kind of error message when adding `Plutarch` as the dependency in [plutus-starter](https://github.com/input-output-hk/plutus-starter)
```
Plutarch/Lift.hs:30:29: error:
    Module ‘PlutusCore.Constant’ does not export ‘readKnownConstant’
   |
30 | import PlutusCore.Constant (readKnownConstant)
   |                             ^^^^^^^^^^^^^^^^^
cabal: Failed to build plutarch-1.1.0 (which is required by
exe:plutus-starter-pab from plutus-starter-0.1.0.0 and
test:plutus-example-projects-test from plutus-starter-0.1.0.0)
```

### Ways to reproduce:
1. git clone https://github.com/input-output-hk/plutus-starter
2. niv add plutonomicon/plutarch --rev 7c6421735de75f76b2c8ecdc441ab1296b5d3f11
3. In the plutus-starter.cabal `library` stanza
```
library
    import: lang
    exposed-modules:
      MyModule
      Plutus.Contracts.Game
    build-depends:
      base >= 4.9 && < 5,
      aeson,
      bytestring,
      containers,
      freer-extras,
      playground-common,
      plutarch,
      plutus-contract,
      plutus-tx-plugin,
      plutus-tx,
      plutus-ledger,
    hs-source-dirs: src examples/src
```
4. In the cabal.project, add one more stanza
```
source-repository-package
  type: git
  location: https://github.com/Plutonomicon/plutarch
  tag: 7c6421735de75f76b2c8ecdc441ab1296b5d3f11
  --sha256: 1vkhcj7rhxdzzxl5mgc1nhj8knvdg33kygw1187m25ckqsb5mnfb
```
5. cabal build

### Questions
It seems like it is a version mismatch between plutarch and plutus-core. May I know what is the minimal version of plutus-core plutarch deverlopers are using? and how do I bump the version in the plutus-starter?

Thank you for your time.

**Comment by L-as** [comment]
You can get it from flake.lock, but do note that you're going to have a bad timo with plutus-starter. Try not to use any of the dependencies from plutus-apps, that will reduce your headache significantly. Separate the cabal projects for onchain and offchain code.

**Comment by TotallyNotChase** [comment]
`plutus-apps` at commit `34fe6eeff441166fee0cd0ceba68c1439f0e93d2` and its relevant dependencies (just copy the `cabal.project` from their repo) should work just fine with Plutarch at `master` (currently).

**Comment by zypeh** [comment]
@L-as I do noticed that, thanks for the sincere advice! I have made one myself using `init-haskell` and use niv to manage my own `cabal.project`. 

@TotallyNotChase Thanks! I can finally build an example using the plutus commit version you have posted.
