### ISSUE TITLE
Tracing and logging.

### ISSUE THREAD

**Issue by delicious-lemon** [Plutonomicon/plutarch#348]
What if we want to trace in production for some reason? Currently this would mean compiling with the `development` flag for release...

What if we want to add a temporary trace as a sanity check that we intend to immediately remove once we have discovered the problem? This currently may involve a recompilation of Plutarch if we are not already in `development` mode.

I suggest we have a trace that always traces. We could have `trace` and `log` for these two styles. I think `log` would make sense as the one controlled by the `development` flag and `trace` should work like `Debug.Trace`.

**Comment by L-as** [comment]
Why would you ever want to trace in production? Anyway, you can make your own `ptrace`.
