### ISSUE TITLE
`plutarch-extra`: export a merged Plutarch Prelude that reexports the base Prelude (or something like Relude?) and the `Plutarch.Prelude`

### ISSUE THREAD

**Issue by MangoIV** [Plutonomicon/plutarch#350]
This increases usability a lot as you can just set this as a Prelude in your cabal file and don't have to import `Plutarch.Prelude` in every file.

**Comment by blamario** [comment]
What happens if the user prefers to work with `PlutusTx.Prelude`?

**Comment by MangoIV** [comment]
If there is a need for that, we can just export another merged `Prelude`, say `PPreludeTx` which reexports that.
I think it's quite handy as the use with `cabal mixins` is really a boost in usability.
