### ISSUE TITLE
Different `golden`s on different `GHC` versions with `development` flag enabled

### ISSUE THREAD

**Issue by MangoIV** [Plutonomicon/plutarch#362]
### Short Description

When running `nix build .#check.x86_64-linux` I have two failing tests because the goldens actually have a different result in the `ghc921` and the `ghc810` tests. 

### Steps to reproduce

Check out `mangoiv/feat_issue_303`, run `nix build .#check.x86_64-linux`. 

Here's also  a link to a failed run on Hercules: 

https://hercules-ci.com/github/Plutonomicon/plutarch/jobs/1053

**Comment by MangoIV** [comment]
![image](https://user-images.githubusercontent.com/40720523/156896376-c6aa44c8-bfb2-4cd0-b68e-707120fb0bac.png)

**Comment by srid** [comment]
Proper fix: #290

Until then you have to either not use do syntax in tests, or make that test spec GHC 9.2 only (eg: see `MonadicSpec.hs`).
