### ISSUE TITLE
`PCurrencySymbol` has requirements violated by `PConstant` instance

### ISSUE THREAD

**Issue by peter-mlabs** [Plutonomicon/plutarch#373]
Currency symbols need to be valid hex:
```
ghci> tn :: Term _ PCurrencySymbol; tn = pconstant "xyz"
ghci> eval tn
*** Exception: not a hexit: 'x'
CallStack (from HasCallStack):
  error, called at src/Data/Either/Extras.hs:6:34 in plutus-ledger-api-0.1.0.0-3i0YDVrhAG5Iv7x6eZ41f0:Data.Either.Extras
```
And need an even number of digits:
```
ghci> tn :: Term _ PCurrencySymbol; tn = pconstant "a"
ghci> eval tn
*** Exception: unpaired digit
CallStack (from HasCallStack):
  error, called at src/Data/Either/Extras.hs:6:34 in plutus-ledger-api-0.1.0.0-3i0YDVrhAG5Iv7x6eZ41f0:Data.Either.Extras
```

Thus, the `pconstant` instance isn't actually valid.

Not a high-priority, but I didn't find this document elsewhere so hopefully this issue will turn up the next time someone tries to search for it.

**Comment by blamario** [comment]
`CurrencySymbol` is just a newtype for `BuiltinByteString`. If we had a `PBuiltinByteString`, what would its `PConstant` instance be?

**Comment by TotallyNotChase** [comment]
This is unfortunately an issue on the Plutus side, not Plutarch side. It's not `pconstant`, that's broken - it's `CurrencySymbol` and its `IsString` implementation. `CurrencySymbol` shouldn't be built using overloaded string at all. You'll observe the same behavior by using an incorrect `CurrencySymbol` on Plutus code.

One solution Plutarch could pursue is to not have `PConstanted PCurrencySymbol` be `CurrencySymbol`. We could make our own `newtype` that doesn't have a implicitly partial `IsString` instance. But this could be quite unergonomic in many cases - as there is no longer a _direct_ relation to `CurrencySymbol` and `PCurrencySymbol` - there's a mediary in between.

Also I believe this applies to several other Plutus ledger types. Everything that's a newtype to a builtin bytestring and derives `IsString` via `LedgerBytes`.

**Comment by peter-mlabs** [comment]
> Also I believe this applies to several other Plutus ledger types. Everything that's a newtype to a builtin bytestring and derives IsString via LedgerBytes.

I _think_ that token names don't have this problem. 

But yes, I think that the way to go would ultimately be diverging from the way Plutus does it, either via the new type or making pconstant behave differently. Is a `PHexByteString` feasible?

Failing any of the above, perhaps it would be possible to log more informative error messages? It's not a _great_ band-aid, but once you're aware of this quirk it's not too burdensome.

**Comment by blamario** [comment]
> I think that token names don't have this problem.

They do: `TokenName` is also just a newtype for `BuiltinByteString`. It's just somewhat less problematic because it can be an arbitrary short `BuiltinByteString` - where short is defined by the current limits of Cardano. An `instance IsString TokenName` is still a bad idea because it has to be partial, not to mention that you have to pick a character encoding.
