### ISSUE TITLE
`ghcid` is broken

### ISSUE THREAD

**Issue by srid** [Plutonomicon/plutarch#382]
After #378, the ghcid commands no longer work:

```sh-session
$ ghcid -c 'cabal repl plutarch-test:exe:plutarch-test' -T Main.main
...
Preprocessing executable 'plutarch-test' for plutarch-test-1.1.0..
GHCi, version 9.2.1: https://www.haskell.org/ghc/  :? for help

<no location info>: error: [-Wmissing-home-modules, -Werror=missing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: 
        Plutarch.FFISpec
Failed, no modules loaded.

No files loaded, GHCi is not working properly.
Command: cabal repl plutarch-test:exe:plutarch-test
```

**Comment by blamario** [comment]
That's what I said on Discord:
> The major problem now is that sydtest-discover is totalitarian. The current hacky workaround only helps the CI, doesn't work inside nix develop.

https://github.com/NorfairKing/sydtest/issues/40

**Comment by srid** [comment]
It does look like we ought to get rid of `sydtest-discover`, but I cannot confirm if that will fix the problem in this case.

**Comment by blamario** [comment]
Fixee by PR #387
