### ISSUE TITLE
`plam` weirdly inferring return type as Haskell function instead of Plutarch function (only without `MonoLocalBinds`)

### ISSUE THREAD

**Issue by TotallyNotChase** [Plutonomicon/plutarch#40]
I finally managed to narrow down a weird behavior I had seen before with `plam`. This only happens after the new `plam` changes-
```hs
foo :: forall s. Term s (PByteString :--> PData :--> PUnit)
foo = plam $ \a b ->
  let
    c = pfstBuiltin #$ pasConstr # b

    f :: Term s (PData :--> PBool)
    f = plam $ \hd ->
      a #== pasByteStr # hd
  in
    pcon PUnit
```

This gives off a-
```
Couldn't match type ‘Term s0 PData -> Term s1 PUnit’
                 with ‘Term s (PData :--> PUnit)’
    arising from a use of ‘plam’
```

It goes away if I remove the type annotation from `f`. I suspect it has something to do with `ScopedTypeVariables`. But then again, I've also seen this error go away by turning on `TypeFamilies` in another place.....

The extensions used here are the same as the ones used in this repo.

Interestingly, the type of `b` on the top level `plam` seems to have been inferred as `Term Any PData`.

Not directly related, but I have also seen the general advice of "giving unused variables explicit types to make `plam` errors go away" [cause unexpected errors](https://github.com/Plutonomicon/plutarch/issues/2#issuecomment-1002154700) to pop up instead. I believe it's related to this issue though.

Edit: Turns out I had `TypeFamilies` **off** when getting this error. Turning it on fixes it. But *why*?

**Comment by TotallyNotChase** [comment]
Looks like the *specific* flag that fixes this is `MonoLocalBinds`, which is implied by `TypeFamilies`.

**Comment by L-as** [comment]
It's likely because you're explicitly writing the `s`. Try replacing it with `_`.

**Comment by TotallyNotChase** [comment]
Replacing the `s` with `_` in `f` doesn't work with the scoped type variable and no `MonoLocalBinds`. It does work by removing the `forall s.` though. Very weird.

In summary; if you get a similar error:
* Turn on `MonoLocalBinds` or some other extension that turns it on (e.g `TypeFamilies`)
* Try not to bring `s` into scope for usage in local binds' typing - leave it as a `_` (use: `PartialTypeSignatures`)

**Comment by TotallyNotChase** [comment]
I will close this in favor of tracking `plam` issues all in #2
