### ISSUE TITLE
Which version of plutus to use?

### ISSUE THREAD

**Issue by AlainMgz** [Plutonomicon/plutarch#408]
Hello,

I've been trying to use plutarch but I can't find a way to compile successfully. I'm using the latest tag in [plutus-apps](https://github.com/input-output-hk/plutus-apps) (v2022-01-17) and the `plutus` version in the plutus-apps' cabal file but it does not work. Tried several other version without success. If someone could fill me in on how to properly install plutarch I'll be grateful. Thanks :)

**Comment by L-as** [comment]
Check the Nix code

**Comment by TotallyNotChase** [comment]
Plutarch `master` should work with [`2a2a7f634e06440de45638c6c613c5428ed7c97d`](https://github.com/input-output-hk/plutus/tree/2a2a7f634e06440de45638c6c613c5428ed7c97d) or somewhere around that commit. That's the latest commit I've tested.
