### ISSUE TITLE
Fill out all of `ScriptContext`

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#43]
We need to mirror https://staging.plutus.iohkdev.io/doc/haddock/plutus-ledger-api/html/Plutus-V1-Ledger-Api.html#t:ScriptContext precisely.

(Do note that this is V1)

**Comment by srid** [comment]
> (Do note that this is V1)

Is the list of tasks to be done in version 1 recorded somewhere? If not, perhaps we can make use of GitHub's Milestone feature (to the right).

**Comment by TotallyNotChase** [comment]
Quick question, let's say I want to fill out the [signatories field in `TxInfo`](https://staging.plutus.iohkdev.io/doc/haddock/plutus-ledger-api/html/Plutus-V1-Ledger-Contexts.html#t:TxInfo), which is a list of [`PubKeyHash`](https://staging.plutus.iohkdev.io/doc/haddock/plutus-ledger-api/html/Plutus-V1-Ledger-Crypto.html#t:PubKeyHash). Would something like this be *the ideal* way to do it-
```hs
newtype PPubKeyHash s = PPubKeyHash (Term s (PAsData PByteString))

instance PlutusType PPubKeyHash where
  type PInner PPubKeyHash _ = PAsData PByteString
  pcon' (PPubKeyHash x) = x
  pmatch' bdata f = f $ PPubKeyHash bdata

data PTxInfo s
  = PTxInfo
      ( Term
          s
          ( PDataList
              '[ PBuiltinList PTxInInfo
               , PBuiltinList PTxOut
               , PValue -- fee
               , PValue -- mint
               , PBuiltinList POpaque -- dcert
               , POpaque -- withdrawals
               , POpaque -- range
               ---- see here  vvv
               , PBuiltinList PPubKeyHash -- signatures
               ---- see here  ^^^
               , POpaque -- data map
               , POpaque -- tx id
               ]
          )
      )
```

**Comment by L-as** [comment]
@TotallyNotChase Another possibility:
```haskell
newtype PPubKeyHash s = PPubKeyHash (Term s PByteString)
  deriving newtype ... via (PAsData PByteString)
```
