### ISSUE TITLE
Complete Plutarch Example, please

### ISSUE THREAD

**Issue by pdavidow** [Plutonomicon/plutarch#432]
Can we have a complete Plutarch example that mimics one of the plutus use-cases, please?

[The closest I found (`simple-escrow`)](https://github.com/V0ldek/plutarch-examples/tree/v0ldek/simple-escrow/src/PlutarchExamples/SimpleEscrow/Validator), is still [incomplete.](https://github.com/V0ldek/plutarch-examples/issues/1#issuecomment-1094360615)

**Comment by TotallyNotChase** [comment]
This is something I have had in mind, definitely - but it's not a high priority task as there is "enough" documentation already and even a few examples out there. Furthermore, those of us working at MLabs also have internal real world Plutarch examples.

Outside of that, [Minswap's open source validators](https://github.com/CatspersCoffee/contracts/blob/main/dex/src/Minswap/BatchOrder/OnChain.hs) have a production grade Plutarch example. Do note that I wrote this when Plutarch 1.1 was just released and therefore may not be entirely idiomatic for Plutarch 1.2.

**Comment by pdavidow** [comment]
An MLabs real world Plutarch example would be just fine.

**Comment by TotallyNotChase** [comment]
Here's a bunch of public examples:-

- https://github.com/samuelWilliams99/plutarch/blob/sam/seabug/plutarch-test/plutarch-base/Plutarch/SeaBugSpec.hs
- https://github.com/mlabs-haskell/plutus-inbox-nfts
- https://github.com/CatspersCoffee/contracts/blob/main/dex/src/Minswap/BatchOrder/OnChain.hs
- https://github.com/Liqwid-Labs/agora/tree/master/agora/Agora
