### ISSUE TITLE
Support latest GHC (currently 9.2.1)

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#46]
Though we can't port the entire Cardano infrastructure to 9.2.1, we can likely take a small subset of the libraries we need and port them.

**Comment by L-as** [comment]
https://github.com/input-output-hk/plutus/issues/4303

**Comment by locallycompact** [comment]
@L-as We can do the whole stack actually, I was working on 9.2.1 in my spare time and basically got as far as plutus and some of that is upstream including cardano-base I think. I neglected to push the build plan from my main machine that gets us to where I got to but I can drop that for you next week.

**Comment by locallycompact** [comment]
@L-as Actually I do have it and it's here https://gitlab.homotopic.tech/templates/plutus-starter/-/tree/ghc-921 

branch ghc-921 `nix build`

**Comment by L-as** [comment]
Wow, huge thanks! I'll definitely look into this (or get someone to do this).

**Comment by L-as** [comment]
@locallycompact Have you considered contributing the changes back upstream? It seems like a ton of patches are required.

**Comment by L-as** [comment]
After looking through this more thoroughly, it seems that most upstream dependencies do support GHC 9.2.1 now without patches. A small subset don't, and we need to contribute back fixes upstream.
