### ISSUE TITLE
 `pparseDatum` throws an error instead of returning `Nothing`

### ISSUE THREAD

**Issue by Bradley-Heather** [Plutonomicon/plutarch#478]
`pparseDatum @MyType # datumHash #$ pfield @"datums" # txinfo`

If there is a Type mismatch between `@MyType` and the datum  of the the corresponding datumHash
`pparseDatum` errors due to ptryfrom  as apposed to returning `Nothing`.

**Comment by Bradley-Heather** [comment]
Ok that makes sense, but at least then I think this should be stated in the description of the function.

The use case in question is searching for a Datum of the correct type within a list of TxOuts.

**Comment by TotallyNotChase** [comment]
That'd be extremely inefficient; there should be a better way to do that depending on the spec of the protocol.

It is technically possible though, though Plutarch currently has no such helpers - you can use the `ChooseData` UPLC builtin function directly and essentially have to write the whole parser for each type similar to `PTryFrom`'s methods.

**Comment by Bradley-Heather** [comment]
Ok great to know. Thanks.
