### ISSUE TITLE
Unlifting script evaluation results to Haskell

### ISSUE THREAD

**Issue by t1lde** [Plutonomicon/plutarch#51]
We can kinda work around it by comparing compiled term representations, but it's going to be pretty necessary to unlift term-encoded values from `Script` evaluation results - mostly for testing.

## Some things I tried

I tried hacking around with this for a while, and got some of the way towards it with `readKnownSelf`, but as usual with plutus-core it was pretty headache inducing.

I also tried going via the `flat` serialization (which I think could also work with Scott-encoded terms), but didn't get too far with that either.

**Comment by TotallyNotChase** [comment]
Relevant: #53

**Comment by srid** [comment]
> `readKnownSelf`

That's interesting, I hadn't seen the `KnownType` constraint in Plutus. In Pluton playground, I used `knownUniOf` in conjunction with a custom type class to associate Haskell values: https://github.com/Plutonomicon/pluton/blob/73e9a6cf055553aca3d01169cd9a9c7fa8aa9f55/src/Pluton/Types/Builtin/Uni.hs#L17

But `readKnownSelf` would obviate all of that.
