### ISSUE TITLE
Add `pconstant` and `plift`

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#53]
```haskell
pconstant :: C a b => a -> Term s b
plift :: C a b => Term s b -> a
```

The typeclass `C` should mirror `DefaultUni`. You could use associated type families rather than functional dependencies.

**Comment by srid** [comment]
This should automatically address #51 right? 

I'm looking at this right now.

**Comment by L-as** [comment]
Probably yeah.

**Comment by srid** [comment]
> `plift :: C a b => Term s b -> a`

What's the exact semantics of `plift` here? Specifically: what is `Term s b`? Is it an arbitrary closed term (if so it must be evaluated), or must it be a constant only?

**Comment by L-as** [comment]
It could theoretically work on open terms too, but it wouldn't be of much use. Let's use `ClosedTerm b` instead.
