### ISSUE TITLE
Add CI to Plutarch

### ISSUE THREAD

**Issue by srid** [Plutonomicon/plutarch#6]
Should run the following in a nix-shell (effectively):

```
./bin/ci-format-check
haskell-language-server
```

Also run `nix build` (ensuring that `cabal test` is run when building the Haskell package for Plutarch).

The current GitHub CI may be replaced.

**Comment by srid** [comment]
> ./bin/ci-format-check

There may be better way to do this.

**Comment by nixinator** [comment]
This is looking like herc-ci + flakes can solve this problem of running tests is herc.

**Comment by srid** [comment]
@nixinator https://hercules-ci.com/github/Plutonomicon/plutarch/jobs/1 should now succeed, now that `master` has a default.nix.

**Comment by nixinator** [comment]
https://hercules-ci.com/github/Plutonomicon/plutarch/jobs/5

`Evaluation failed
Please make sure your ci.nix has at least one derivation.`

https://docs.hercules-ci.com/hercules-ci/troubleshooting/#why-is-my-attribute-not-in-eval

hmmmm, must be the structure of this flake. Investigating.

**Comment by srid** [comment]
There is a `default.nix` in the repo and Hercules _should_ be using it,
https://docs.hercules-ci.com/hercules-ci-agent/evaluation/

> At the top-level of your repository, the agent will search for a Nix file to evaluate in the following order: nix/ci.nix, ci.nix or default.nix

Sounds like an upstream regression to me. Does Robert know?

**Comment by srid** [comment]
Oh https://github.com/hercules-ci/flake-compat-ci

See #10

**Comment by L-as** [comment]
Thank you @MatthewCroughan for https://github.com/NixOS/templates/pull/12

**Comment by nixinator** [comment]
> Thank you @MatthewCroughan for [NixOS/templates#12](https://github.com/NixOS/templates/pull/12)

``` ______________ 
< nice one Las >
 -------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

```
