### ISSUE TITLE
Make ImportQualifiedPost the default (or remove it entirely)

### ISSUE THREAD

**Issue by srid** [Plutonomicon/plutarch#61]
~~The project inconsistently uses `ImportQualifiedPost`,~~ which breaks idempotency of fourmolu. ~~Enable ImportQualifiedPost throughout, and add it to .cabal file, if we are using it.~~

**Comment by srid** [comment]
Actually, here's what is happening:

.cabal file already has `ImportQualifiedPost` enabled. And this forces `formolu` (at least as used by HLS) to rewrite the imports to put `qualified` in post position.

In my branch I'm working around this by just removing the extension from the `default-extensions` list.

**Comment by L-as** [comment]
I can't see anywhere where we're using `ImportQualifiedPost`, though we have the extension enabled.
