### ISSUE TITLE
General guide for Haskell-functions vs Plutarch-level functions

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#78]
I've been thinking about this wrt. #76 

I somewhat incorrectly assumed that making the functions Haskell-level would be better, but now that I think about this more, this is much more complex. See e.g. https://github.com/Plutonomicon/plutarch/blob/4528d3beb5bbcd35be0b1f48a25a195e6abe3d7c/Plutarch/List.hs#L157

In the body of `pfoldr`, we mention the function `f`. If this were a Haskell-level function, it would be unconditionally inlined.
This is inobviously often problematic, because it will mean a different top-level function is generated for each function passed, i.e. it is **monomorphised**. We often do not want monomorphisation because we care about size more than CPU.

In general, functions should generally try to be as small as possible, and that is why e.g. `pelimList` should take Haskell-level functions: https://github.com/Plutonomicon/plutarch/blob/4528d3beb5bbcd35be0b1f48a25a195e6abe3d7c/Plutarch/List.hs#L92

Were they not Haskell-level, extra `plam`s would have to be introduced.

One possible optimisation that we don't perform today is inlining the function passed to a hoisted HOF if that HOF is inlined due to only being used once. This is not trivial because it will mean we have to perform analysis of the body of the HOF to find out whether it's worth it.

CC @TotallyNotChase

**Comment by TotallyNotChase** [comment]
Definitely want to experiment on this a bit more in parallel with #79 and put it in the guide.

It should be noted that the guide currently says "prefer Plutarch level functions". I still think this is true in many cases - but I'll also extend it with aforementioned information.
