### ISSUE TITLE
All script evaluation with `evaluateScript` fails

### ISSUE THREAD

**Issue by srid** [Plutonomicon/plutarch#9]
`eval` or `evalWithArgs` returns:

```
(MalformedScript "FreeIndex 0")
```

See #8 to reproduce.

**Comment by L-as** [comment]
@srid I recommend reading the paper referenced in that file. I do not believe that there is an issue with script compilation, it is likely an issue with the way scripts are evaluated using that function. If you look at the output, the output is correct.

**Comment by srid** [comment]
I'll check it out, but note that Plutarch generates a UPLC different to that of Pluto (see the debruijin indices of the two vars inside). Also, `evaluateScript` is verbatim from Plutus; we did not change the semantics of evaluation.

---

**Pluto** (```(\x y -> x `AddInteger` y)```:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/3998/146093016-6acae120-5d48-4b05-87de-7915f83198c3.png">

---

**Plutarch** (`plam $ \x y -> x + y`):

<img width="357" alt="image" src="https://user-images.githubusercontent.com/3998/146093175-7ef83e38-6b19-4632-9f35-a23e91b2d056.png">

**Comment by L-as** [comment]
To give more information: Essentially it seems that the authors of Plutus think that `Natural` starts from 1, when it in fact starts from 0.
