### ISSUE TITLE
Guide: Explain how to hoist operators

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#92]
Operators have to be Haskell-terms due to limitations in the Haskell language (unfortunately).

An operator `x O y` can be hoisted as such: `x O y = (\f -> f # x # y) $ phoistAcyclic $ ...`

**Comment by TotallyNotChase** [comment]
I think `pand`/`por` and their operator versions would be good examples as well.

I'll add this to the "tips and tricks" section.

**Comment by TotallyNotChase** [comment]
Wait I just realized the guide already notes this in [here](https://github.com/Plutonomicon/plutarch/blob/master/docs/GUIDE.md#prefer-plutarch-level-functions)

**Comment by TotallyNotChase** [comment]
Maybe I should make it a bit clearer and put it in the "Hoisting" section under concepts

**Comment by L-as** [comment]
One thing that might be useful to note is that you don't need to export the Plutarch-level function. `plam $ \x y -> pand # x # y` will be optimised into `pand` after all if `pand` is hoisted.
