### ISSUE TITLE
Convenient field accessors for use with API types

### ISSUE THREAD

**Issue by t1lde** [Plutonomicon/plutarch#95]
The API types are still pretty rough to use IMO, the dance with `pmatch` and such is pretty messy, and `PAsData` also adds some noise.

To address this, I want to extend `DataRepr` with named fields, so we can have something that looks like:

```haskell
pfield #fieldName :: (Term s (r :--> a))
```

that can also work over `PAsData`:

```haskell
pfield #fieldName :: (Term s (r :--> PAsData a))
```

This could be used like:

```haskell
x & pfield #fieldName
```
, or perhaps with an operator that applies the value:

```haskell
x #. #fieldName
```

Which can also support RDS:

```haskell
x.fieldName
```

it would also be nice to have numbered fields for `PIsDataRepr` types without field names, and for `PDataList`, which would be useful when matching sum types. 

Perhaps, if the type-level stuff works out:

```haskell
pfield #0 :: (Term s (r :--> a))
```

**Comment by L-as** [comment]
Indexing the data list is always suboptimal because it will lead to excess code. There might still be a way to express field names however. An easy solution is to just use newtypes.

**Comment by t1lde** [comment]
the cost of indexing field names should be relatively constant over most scripts, with hoisting.

I'm not sure what a smaller alternative would be, aside from maybe repeatedly getting the head of the DataList in some cases...

**Comment by L-as** [comment]
Accessing all n elements of a record will use O(n^2) CPU if all elements are accessed using indexing. The accessor functions can be shared across all data structures, but it's still far from optimal.

**Comment by L-as** [comment]
I think it's possible to make an HList-like type such that you can take the first N elements from the `PDataList` and be able to access the fields using the `HasField` type class. It would generate exactly N calls to `HeadList`.

**Comment by L-as** [comment]
Another partial solution is to always take all N fields, which would simplify the types.

**Comment by L-as** [comment]
FWIW since we have GHC 9 now we can use record dot syntax.
