### ISSUE TITLE
Fix Plutarch.Api.V1

### ISSUE THREAD

**Issue by L-as** [Plutonomicon/plutarch#96]
Currently there are a bunch of bugs in it.

For example, the lists are not `PBuiltinList` but `PList`, in addition all the elements must be of the form `PAsData a`.

**Comment by t1lde** [comment]
`PList` is just a synonym for `PBuiltinList (PAsData a)`, perhaps it should have been given a different name to avoid clashing with the Scott-encoded version...

Not sure what you mean about PAsData,

**Comment by L-as** [comment]
This is my mistake then. If assumed it wasn't a synonym.
